/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.eployees.salary;

import app.eployees.salary.bean.PhanXuong;
import app.eployees.salary.render.PhanXuongComboboxModel;
import app.eployees.salary.utils.UtilsClass;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author vuongluis
 */
public class AppEployeesSalary extends javax.swing.JFrame {

    /**
     * Creates new form AppEployeesSalary
     */
    private ArrayList<String> list = new ArrayList<String>();
    
    public AppEployeesSalary() {
        initComponents();
        ImageIcon image = new ImageIcon(getClass().getResource("/images/logo.png"));
        this.setIconImage(image.getImage());
        cbPhanXuong.setModel(new PhanXuongComboboxModel());
        PhanXuong objectx = (PhanXuong) new PhanXuongComboboxModel().getElementAt(cbPhanXuong.getSelectedIndex());
        tfSoSPC.setText(String.valueOf(objectx.getSoSPC()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        maNV = new javax.swing.JLabel();
        tfTienLuong = new javax.swing.JTextField();
        soSP = new javax.swing.JLabel();
        tfMaNV = new javax.swing.JTextField();
        phanXuong = new javax.swing.JLabel();
        cbPhanXuong = new javax.swing.JComboBox();
        soSPC = new javax.swing.JLabel();
        tfSoSPC = new javax.swing.JTextField();
        tienLuong = new javax.swing.JLabel();
        tfSoSP = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnTinh = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        ttNhanVien = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfInfor = new javax.swing.JTextArea();
        tfSPC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                          Quản lý nhân viên - VinaENTER EDU");
        setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(505, 585));
        setMinimumSize(new java.awt.Dimension(505, 585));
        setName("frame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setName("panel"); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý nhân viên");
        jLabel1.setPreferredSize(new java.awt.Dimension(390, 22));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(177, 18, 170, 30);
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        maNV.setForeground(new java.awt.Color(255, 255, 255));
        maNV.setText("Mã nhân viên:");
        jPanel1.add(maNV);
        maNV.setBounds(71, 80, 80, 20);

        tfTienLuong.setEditable(false);
        tfTienLuong.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.background")));
        jPanel1.add(tfTienLuong);
        tfTienLuong.setBounds(153, 206, 258, 33);

        soSP.setForeground(new java.awt.Color(255, 255, 255));
        soSP.setText("Số sản phẩm:");
        soSP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(soSP);
        soSP.setBounds(71, 122, 80, 20);

        tfMaNV.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Button.background"), 1, true));
        jPanel1.add(tfMaNV);
        tfMaNV.setBounds(153, 77, 258, 33);

        phanXuong.setForeground(new java.awt.Color(255, 255, 255));
        phanXuong.setText("Phân xưởng:");
        jPanel1.add(phanXuong);
        phanXuong.setBounds(71, 166, 70, 20);

        cbPhanXuong.setForeground(new java.awt.Color(255, 255, 255));
        cbPhanXuong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPhanXuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPhanXuongActionPerformed(evt);
            }
        });
        jPanel1.add(cbPhanXuong);
        cbPhanXuong.setBounds(153, 164, 79, 32);

        soSPC.setForeground(new java.awt.Color(255, 255, 255));
        soSPC.setText("Số sản phẩm chuẩn:");
        soSPC.setDoubleBuffered(true);
        soSPC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(soSPC);
        soSPC.setBounds(248, 166, 120, 20);

        tfSoSPC.setEditable(false);
        tfSoSPC.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.background")));
        jPanel1.add(tfSoSPC);
        tfSoSPC.setBounds(372, 164, 40, 32);

        tienLuong.setForeground(new java.awt.Color(255, 255, 255));
        tienLuong.setText("Tiền lương:");
        jPanel1.add(tienLuong);
        tienLuong.setBounds(71, 211, 70, 20);

        tfSoSP.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.background")));
        jPanel1.add(tfSoSP);
        tfSoSP.setBounds(153, 120, 258, 33);

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setForeground(new java.awt.Color(51, 102, 255));
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem);
        btnThem.setBounds(263, 258, 59, 28);

        btnTinh.setBackground(new java.awt.Color(255, 255, 255));
        btnTinh.setForeground(new java.awt.Color(51, 102, 255));
        btnTinh.setText("Tính lương");
        btnTinh.setBorder(null);
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });
        jPanel1.add(btnTinh);
        btnTinh.setBounds(161, 258, 90, 28);

        btnThoat.setBackground(new java.awt.Color(255, 255, 255));
        btnThoat.setForeground(new java.awt.Color(51, 102, 255));
        btnThoat.setText("Thoát");
        btnThoat.setBorder(null);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat);
        btnThoat.setBounds(334, 258, 59, 28);

        ttNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        ttNhanVien.setText("Thông tin nhân viên:");
        jPanel1.add(ttNhanVien);
        ttNhanVien.setBounds(71, 308, 120, 20);

        tfInfor.setColumns(22);
        tfInfor.setRows(5);
        tfInfor.setWrapStyleWord(true);
        jScrollPane3.setViewportView(tfInfor);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(66, 336, 350, 180);

        tfSPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(tfSPC);
        tfSPC.setBounds(0, 0, 510, 590);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        File file = new File("nhanvien.dat");
        if(!file.exists()){
            try {
                file.createNewFile();
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        }
        try{
            BufferedWriter br = new BufferedWriter(new FileWriter(file.getAbsolutePath()));
            for (String string : list) {
                br.write(string);
                br.newLine();
            }
            br.close();
        }catch(IOException exx){
            System.out.println(exx.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        int soSP = 0;
        if(tfMaNV.getText().isEmpty()){
            JOptionPane.showMessageDialog(new AppEployeesSalary(), "Nhập mã nhân viên","Thông báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        try{
            if(tfSoSP.getText().isEmpty()){
                JOptionPane.showMessageDialog(new AppEployeesSalary(), "Nhập vào số sản phẩm","Thông báo",JOptionPane.WARNING_MESSAGE);
                return;
            }
            soSP = Integer.parseInt(tfSoSP.getText());
        }catch(NumberFormatException exx){
            JOptionPane.showMessageDialog(new AppEployeesSalary(), "Nhập số sản phẩm là số","Thông báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        PhanXuong objecty = (PhanXuong) new PhanXuongComboboxModel().getElementAt(cbPhanXuong.getSelectedIndex());
        int soSPC = Integer.parseInt(tfSoSPC.getText());
        int cost1 = 20000;
        int cost2 = 30000;
        if("A".equals(objecty.getName())){
            if(soSPC < soSP){
                String result = String.valueOf(soSPC*cost1 + (soSP - soSPC)*cost2);
                tfTienLuong.setText(new UtilsClass().changeCurrencyVND(result)+" VND");
            }else{
                String result = String.valueOf((soSPC - soSP)*cost2);
                tfTienLuong.setText(new UtilsClass().changeCurrencyVND(result)+" VND");
            }
        }else if("B".equals(objecty.getName())){
           if(soSPC < soSP){
                String result = String.valueOf(soSPC*cost1 + (soSP - soSPC)*cost2);
                tfTienLuong.setText(new UtilsClass().changeCurrencyVND(result)+" VND");
            }else{
                String result = String.valueOf((soSPC - soSP)*cost2);
                tfTienLuong.setText(new UtilsClass().changeCurrencyVND(result)+" VND");
            }
        }else if("C".equals(objecty.getName())){
           if(soSPC < soSP){
                String result = String.valueOf(soSPC*cost1 + (soSP - soSPC)*cost2);
                tfTienLuong.setText(new UtilsClass().changeCurrencyVND(result)+" VND");
            }else{
                String result = String.valueOf((soSPC - soSP)*cost2);
                tfTienLuong.setText(new UtilsClass().changeCurrencyVND(result)+" VND");
            }
        }else if("D".equals(objecty.getName())){
           if(soSPC < soSP){
                String result = String.valueOf(soSPC*cost1 + (soSP - soSPC)*cost2);
                tfTienLuong.setText(new UtilsClass().changeCurrencyVND(result)+" VND");
            }else{
                String result = String.valueOf((soSPC - soSP)*cost2);
                tfTienLuong.setText(new UtilsClass().changeCurrencyVND(result)+" VND");
            }
        }
    }//GEN-LAST:event_btnTinhActionPerformed

    private void cbPhanXuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPhanXuongActionPerformed
        PhanXuong phanXuong = (PhanXuong) new PhanXuongComboboxModel().getElementAt(cbPhanXuong.getSelectedIndex());
        if("A".equals(phanXuong.getName())){
            tfSoSPC.setText(String.valueOf(phanXuong.getSoSPC()));
        }else if("B".equals(phanXuong.getName())){
            tfSoSPC.setText(String.valueOf(phanXuong.getSoSPC()));
        }else if("C".equals(phanXuong.getName())){
            tfSoSPC.setText(String.valueOf(phanXuong.getSoSPC()));
        }else if("D".equals(phanXuong.getName())){
            tfSoSPC.setText(String.valueOf(phanXuong.getSoSPC()));
        }
    }//GEN-LAST:event_cbPhanXuongActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        int soSP = 0;
        if(tfMaNV.getText().isEmpty()){
            JOptionPane.showMessageDialog(new AppEployeesSalary(), "Nhập mã nhân viên","Thông báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        try{
            if(tfSoSP.getText().isEmpty()){
                JOptionPane.showMessageDialog(new AppEployeesSalary(), "Nhập vào số sản phẩm","Thông báo",JOptionPane.WARNING_MESSAGE);
                return;
            }
            soSP = Integer.parseInt(tfSoSP.getText());
        }catch(NumberFormatException exx){
            JOptionPane.showMessageDialog(new AppEployeesSalary(), "Nhập số sản phẩm là số","Thông báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        PhanXuong objecty = (PhanXuong) new PhanXuongComboboxModel().getElementAt(cbPhanXuong.getSelectedIndex());
        int soSPC = Integer.parseInt(tfSoSPC.getText());
        int cost1 = 20000;
        int cost2 = 30000;
        String outString = "Mã NV: "+tfMaNV.getText()+" - Số SP: "+soSP+" - Phân xưởng: "+objecty.getName()+" - Tiền lương: ";
        if("A".equals(objecty.getName())){
            if(soSPC < soSP){
                String result = String.valueOf(soSPC*cost1 + (soSP - soSPC)*cost2);
                outString += new UtilsClass().changeCurrencyVND(result)+" VND";
            }else{
                String result = String.valueOf((soSPC - soSP)*cost2);
                outString += new UtilsClass().changeCurrencyVND(result)+" VND";
            }
        }else if("B".equals(objecty.getName())){
           if(soSPC < soSP){
                String result = String.valueOf(soSPC*cost1 + (soSP - soSPC)*cost2);
                outString += new UtilsClass().changeCurrencyVND(result)+" VND";
            }else{
                String result = String.valueOf((soSPC - soSP)*cost2);
                outString += new UtilsClass().changeCurrencyVND(result)+" VND";
            }
        }else if("C".equals(objecty.getName())){
           if(soSPC < soSP){
                String result = String.valueOf(soSPC*cost1 + (soSP - soSPC)*cost2);
                outString += new UtilsClass().changeCurrencyVND(result)+" VND";
            }else{
                String result = String.valueOf((soSPC - soSP)*cost2);
                outString += new UtilsClass().changeCurrencyVND(result)+" VND";
            }
        }else if("D".equals(objecty.getName())){
           if(soSPC < soSP){
                String result = String.valueOf(soSPC*cost1 + (soSP - soSPC)*cost2);
                outString += new UtilsClass().changeCurrencyVND(result)+" VND";
            }else{
                String result = String.valueOf((soSPC - soSP)*cost2);
                outString += new UtilsClass().changeCurrencyVND(result)+" VND";
            }
        }
        tfInfor.append(outString+"\n");
        list.add(outString);
    }//GEN-LAST:event_btnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppEployeesSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppEployeesSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppEployeesSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppEployeesSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppEployeesSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTinh;
    private javax.swing.JComboBox cbPhanXuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel maNV;
    private javax.swing.JLabel phanXuong;
    private javax.swing.JLabel soSP;
    private javax.swing.JLabel soSPC;
    private javax.swing.JTextArea tfInfor;
    private javax.swing.JTextField tfMaNV;
    private javax.swing.JLabel tfSPC;
    private javax.swing.JTextField tfSoSP;
    private javax.swing.JTextField tfSoSPC;
    private javax.swing.JTextField tfTienLuong;
    private javax.swing.JLabel tienLuong;
    private javax.swing.JLabel ttNhanVien;
    // End of variables declaration//GEN-END:variables
}
