/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.eployees.salary;

import javax.swing.ImageIcon;

/**
 *
 * @author vuongluis
 */
public class AppEployeesSalary extends javax.swing.JFrame {

    /**
     * Creates new form AppEployeesSalary
     */
    public AppEployeesSalary() {
        initComponents();
        ImageIcon image = new ImageIcon(getClass().getResource("/images/logo.png"));
        this.setIconImage(image.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        maNV = new javax.swing.JLabel();
        tfTienLuong = new javax.swing.JTextField();
        soSP = new javax.swing.JLabel();
        tfMaNV = new javax.swing.JTextField();
        phanXuong = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        soSPC = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        tienLuong = new javax.swing.JLabel();
        tfSoSP = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnTinh = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        ttNhanVien = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfInfor = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                          Quản lý nhân viên - VinaENTER EDU");
        setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(505, 585));
        setMinimumSize(new java.awt.Dimension(505, 585));
        setName("frame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setName("panel"); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý nhân viên");
        jLabel1.setPreferredSize(new java.awt.Dimension(390, 22));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(177, 18, 170, 30);
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        maNV.setForeground(new java.awt.Color(255, 255, 255));
        maNV.setText("Mã nhân viên:");
        jPanel1.add(maNV);
        maNV.setBounds(71, 80, 80, 20);

        tfTienLuong.setEditable(false);
        tfTienLuong.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.background")));
        jPanel1.add(tfTienLuong);
        tfTienLuong.setBounds(153, 206, 258, 33);

        soSP.setForeground(new java.awt.Color(255, 255, 255));
        soSP.setText("Số sản phẩm:");
        soSP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(soSP);
        soSP.setBounds(71, 122, 80, 20);

        tfMaNV.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Button.background"), 1, true));
        jPanel1.add(tfMaNV);
        tfMaNV.setBounds(153, 77, 258, 33);

        phanXuong.setForeground(new java.awt.Color(255, 255, 255));
        phanXuong.setText("Phân xưởng:");
        jPanel1.add(phanXuong);
        phanXuong.setBounds(71, 166, 70, 20);

        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(153, 164, 79, 32);

        soSPC.setForeground(new java.awt.Color(255, 255, 255));
        soSPC.setText("Số sản phẩm chuẩn:");
        soSPC.setDoubleBuffered(true);
        soSPC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(soSPC);
        soSPC.setBounds(248, 166, 120, 20);

        jTextField1.setEditable(false);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.background")));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(372, 164, 40, 32);

        tienLuong.setForeground(new java.awt.Color(255, 255, 255));
        tienLuong.setText("Tiền lương:");
        jPanel1.add(tienLuong);
        tienLuong.setBounds(71, 211, 70, 20);

        tfSoSP.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.background")));
        jPanel1.add(tfSoSP);
        tfSoSP.setBounds(153, 120, 258, 33);

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setForeground(new java.awt.Color(51, 102, 255));
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        jPanel1.add(btnThem);
        btnThem.setBounds(263, 258, 59, 28);

        btnTinh.setBackground(new java.awt.Color(255, 255, 255));
        btnTinh.setForeground(new java.awt.Color(51, 102, 255));
        btnTinh.setText("Tính lương");
        btnTinh.setBorder(null);
        jPanel1.add(btnTinh);
        btnTinh.setBounds(161, 258, 90, 28);

        btnThoat.setBackground(new java.awt.Color(255, 255, 255));
        btnThoat.setForeground(new java.awt.Color(51, 102, 255));
        btnThoat.setText("Thoát");
        btnThoat.setBorder(null);
        jPanel1.add(btnThoat);
        btnThoat.setBounds(334, 258, 59, 28);

        ttNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        ttNhanVien.setText("Thông tin nhân viên:");
        jPanel1.add(ttNhanVien);
        ttNhanVien.setBounds(71, 308, 120, 20);

        tfInfor.setColumns(20);
        tfInfor.setLineWrap(true);
        tfInfor.setRows(5);
        tfInfor.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tfInfor);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 340, 340, 190);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\ManagerGit\\DanisLuis5\\App-EmployeesSalary\\src\\images\\background.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -10, 510, 600);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppEployeesSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppEployeesSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppEployeesSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppEployeesSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppEployeesSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTinh;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel maNV;
    private javax.swing.JLabel phanXuong;
    private javax.swing.JLabel soSP;
    private javax.swing.JLabel soSPC;
    private javax.swing.JTextArea tfInfor;
    private javax.swing.JTextField tfMaNV;
    private javax.swing.JTextField tfSoSP;
    private javax.swing.JTextField tfTienLuong;
    private javax.swing.JLabel tienLuong;
    private javax.swing.JLabel ttNhanVien;
    // End of variables declaration//GEN-END:variables
}
